#!/usr/bin/env python

# This service script does nothing more that (re)starting, stopping and
# giving the status of the FFF Simulator.
# The actual fff_simulator.py should be in the path or explicitely specified
# here.

import sys
import logging
sys.path.append('/opt/fff_simulator/')
from fff_simulator import FFFSimulator

if __name__ == "__main__":
    daemon = FFFSimulator('/tmp/fff_simulator.pid')
    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            logging.info("Starting daemon.")
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
            logging.info("Daemon stopped.")
        elif 'restart' == sys.argv[1]:
            logging.info("Restarting daemon.")
            daemon.restart()
        elif 'status' == sys.argv[1]:
            daemon.status()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "usage: %s start|stop|restart|status" % sys.argv[0]
        sys.exit(2)
